import { User, LostFoundItem, Claim, Notification, Announcement } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Alex Johnson',
    email: 'alex.johnson@university.edu',
    role: 'student',
    department: 'Computer Science',
    studentId: 'CS2021001',
    joinedAt: '2024-01-15',
  },
  {
    id: 'u2',
    name: 'Maria Garcia',
    email: 'maria.garcia@university.edu',
    role: 'student',
    department: 'Business Administration',
    studentId: 'BA2022034',
    joinedAt: '2024-02-10',
  },
  {
    id: 'admin1',
    name: 'Dr. Robert Chen',
    email: 'r.chen@university.edu',
    role: 'admin',
    department: 'Security Office',
    studentId: 'STAFF001',
    joinedAt: '2023-08-01',
  },
];

export const MOCK_ITEMS: LostFoundItem[] = [
  {
    id: 'item1',
    type: 'lost',
    title: 'Black MacBook Pro 14"',
    description: 'Lost my MacBook Pro in the library. It has a blue sticker on the back and a cracked corner. Very important for my thesis work.',
    category: 'Electronics',
    date: '2025-01-14',
    time: '14:30',
    location: 'Main Library - 2nd Floor',
    images: [],
    priority: 'urgent',
    status: 'active',
    reportedBy: 'u1',
    reporterName: 'Alex Johnson',
    reporterEmail: 'alex.johnson@university.edu',
    createdAt: '2025-01-14T14:45:00Z',
  },
  {
    id: 'item2',
    type: 'found',
    title: 'Student ID Card',
    description: 'Found a student ID card near the cafeteria entrance. The name on the card is partially visible.',
    category: 'Documents',
    date: '2025-01-14',
    time: '12:00',
    location: 'University Cafeteria - Main Entrance',
    images: [],
    priority: 'normal',
    status: 'active',
    reportedBy: 'u2',
    reporterName: 'Maria Garcia',
    reporterEmail: 'maria.garcia@university.edu',
    createdAt: '2025-01-14T12:15:00Z',
  },
  {
    id: 'item3',
    type: 'lost',
    title: 'Blue Denim Jacket',
    description: 'Left my blue denim jacket in the lecture hall after the morning class. Has my name written inside the collar.',
    category: 'Clothing',
    date: '2025-01-13',
    time: '10:00',
    location: 'Science Building - Lecture Hall B',
    images: [],
    priority: 'normal',
    status: 'active',
    reportedBy: 'u2',
    reporterName: 'Maria Garcia',
    reporterEmail: 'maria.garcia@university.edu',
    createdAt: '2025-01-13T10:30:00Z',
  },
  {
    id: 'item4',
    type: 'found',
    title: 'Set of Keys (3 keys)',
    description: 'Found a keychain with 3 keys and a small red keychain tag near the parking lot.',
    category: 'Keys',
    date: '2025-01-13',
    time: '16:00',
    location: 'Student Parking Lot A',
    images: [],
    priority: 'normal',
    status: 'active',
    reportedBy: 'u1',
    reporterName: 'Alex Johnson',
    reporterEmail: 'alex.johnson@university.edu',
    createdAt: '2025-01-13T16:20:00Z',
  },
  {
    id: 'item5',
    type: 'lost',
    title: 'Apple AirPods Pro',
    description: 'Lost white AirPods Pro case. Has a small scratch on the lid. Last seen at the gym.',
    category: 'Electronics',
    date: '2025-01-12',
    time: '18:00',
    location: 'University Gym',
    images: [],
    priority: 'urgent',
    status: 'claimed',
    reportedBy: 'u1',
    reporterName: 'Alex Johnson',
    reporterEmail: 'alex.johnson@university.edu',
    createdAt: '2025-01-12T18:30:00Z',
  },
  {
    id: 'item6',
    type: 'found',
    title: 'Purple Backpack',
    description: 'Found a purple backpack with books and stationery inside near the engineering building.',
    category: 'Bags',
    date: '2025-01-12',
    time: '09:00',
    location: 'Engineering Building - Lobby',
    images: [],
    priority: 'normal',
    status: 'active',
    reportedBy: 'u2',
    reporterName: 'Maria Garcia',
    reporterEmail: 'maria.garcia@university.edu',
    createdAt: '2025-01-12T09:15:00Z',
  },
  {
    id: 'item7',
    type: 'lost',
    title: 'Calculator (Casio FX-991)',
    description: 'Scientific calculator lost during the math exam. Has initials "MG" written on the back.',
    category: 'Electronics',
    date: '2025-01-11',
    time: '11:30',
    location: 'Math Department - Room 204',
    images: [],
    priority: 'urgent',
    status: 'returned',
    reportedBy: 'u2',
    reporterName: 'Maria Garcia',
    reporterEmail: 'maria.garcia@university.edu',
    createdAt: '2025-01-11T12:00:00Z',
  },
  {
    id: 'item8',
    type: 'found',
    title: 'Prescription Glasses',
    description: 'Found black-framed prescription glasses in a brown case near the library exit.',
    category: 'Accessories',
    date: '2025-01-10',
    time: '17:00',
    location: 'Main Library - Exit',
    images: [],
    priority: 'normal',
    status: 'active',
    reportedBy: 'u1',
    reporterName: 'Alex Johnson',
    reporterEmail: 'alex.johnson@university.edu',
    createdAt: '2025-01-10T17:30:00Z',
  },
];

export const MOCK_CLAIMS: Claim[] = [
  {
    id: 'claim1',
    itemId: 'item5',
    itemTitle: 'Apple AirPods Pro',
    itemType: 'lost',
    claimantId: 'u1',
    claimantName: 'Alex Johnson',
    claimantEmail: 'alex.johnson@university.edu',
    description: 'These are my AirPods. I lost them at the gym on Monday evening.',
    proofDescription: 'The serial number is visible on the inside of the case lid. I also have the purchase receipt.',
    status: 'approved',
    submittedAt: '2025-01-13T09:00:00Z',
    updatedAt: '2025-01-13T14:00:00Z',
    adminNote: 'Verified via serial number. Please collect from Security Office.',
  },
  {
    id: 'claim2',
    itemId: 'item2',
    itemTitle: 'Student ID Card',
    itemType: 'found',
    claimantId: 'u2',
    claimantName: 'Maria Garcia',
    claimantEmail: 'maria.garcia@university.edu',
    description: 'I believe this is my ID card. I lost it near the cafeteria yesterday.',
    proofDescription: 'My student ID number is BA2022034. I can provide my university enrollment letter.',
    status: 'pending',
    submittedAt: '2025-01-14T15:00:00Z',
    updatedAt: '2025-01-14T15:00:00Z',
  },
  {
    id: 'claim3',
    itemId: 'item7',
    itemTitle: 'Calculator (Casio FX-991)',
    itemType: 'lost',
    claimantId: 'u2',
    claimantName: 'Maria Garcia',
    claimantEmail: 'maria.garcia@university.edu',
    description: 'This is my calculator. I had my initials engraved on the back.',
    proofDescription: 'Initials MG are on the back. I also have the store receipt from Campus Store.',
    status: 'resolved',
    submittedAt: '2025-01-12T08:00:00Z',
    updatedAt: '2025-01-12T16:00:00Z',
    adminNote: 'Item returned to owner. Case closed.',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif1',
    userId: 'u1',
    title: '🎯 Possible Match Found!',
    body: 'A found item "MacBook" matches your lost item report. Check it out!',
    type: 'match',
    read: false,
    createdAt: '2025-01-14T16:00:00Z',
    itemId: 'item1',
  },
  {
    id: 'notif2',
    userId: 'u1',
    title: '✅ Claim Approved',
    body: 'Your claim for AirPods Pro has been approved. Please collect from Security Office.',
    type: 'claim',
    read: false,
    createdAt: '2025-01-13T14:00:00Z',
    itemId: 'item5',
  },
  {
    id: 'notif3',
    userId: 'u1',
    title: '📢 Announcement',
    body: 'Multiple ID cards found near the Admin Block. Please visit Security Office to claim.',
    type: 'announcement',
    read: true,
    createdAt: '2025-01-12T10:00:00Z',
  },
  {
    id: 'notif4',
    userId: 'u2',
    title: '📋 Claim Under Review',
    body: 'Your claim for Student ID Card is being reviewed by admin.',
    type: 'claim',
    read: false,
    createdAt: '2025-01-14T15:30:00Z',
    itemId: 'item2',
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann1',
    title: '📢 Found: Multiple ID Cards',
    body: 'Several student ID cards have been found near the Admin Block. Visit the Security Office with proof of identity to claim yours.',
    createdAt: '2025-01-12T10:00:00Z',
    adminName: 'Dr. Robert Chen',
  },
  {
    id: 'ann2',
    title: '⚠️ Lost & Found Office Hours',
    body: 'The Lost & Found office will be open Monday to Friday, 9 AM to 5 PM. Weekend hours are 10 AM to 2 PM.',
    createdAt: '2025-01-10T08:00:00Z',
    adminName: 'Dr. Robert Chen',
  },
  {
    id: 'ann3',
    title: '🔔 Items Expiring Soon',
    body: 'Items not claimed within 30 days will be donated. Please check if any of your lost items have been found.',
    createdAt: '2025-01-08T09:00:00Z',
    adminName: 'Dr. Robert Chen',
  },
];
